### ISSUE TITLE
pre-commit hook usage with virtualenv fails

### ISSUE THREAD

**Issue by zjpiazza** [pdoc3/pdoc#313]
### Expected Behavior

After running pre-commit hook, to have generated pdoc output in the directory

### Actual Behavior

ModuleNotFoundError is raised when running the pdoc pre-commit hook

### Steps to Reproduce

1. Install pre-commit framework
2. Add pdoc to .pre-commit-config.yaml hooks
3. Install pre-commit hooks
4. Run the command "pre-commit run --all-files"

### Additional info

- pdoc version: 0.9.2

**Comment by xcodz-dot** [comment]
please share the .pre-commit-config.yaml file where you have added pdoc hook and possibly the github project link if the project is public

**Comment by Ricocotam** [comment]
I'm having the same issue, here is my pre-commit (only pdoc related) :

```
-   repo: https://github.com/pdoc3/pdoc
    rev: master
    hooks:
    -   id: pdoc
        name: pdoc
        description: 'pdoc: Auto-generate API documentation for Python projects'
        entry: pdoc --html -f -o docs module1 module2 module3
        language: python
        language_version: python3
        require_serial: true
        types: [python]
        always_run: true
```

I have some packages installed that are out of stdlib that raise `ModyleNotfoundError`. I didn't take time to replicate with minimal version but it should be easy : 

+ Create new git project
+ Create virtualenv
+ install pre-commit hook
+ add the hook as described above (a single module is enough, even a single file)
+ pip install (using virtualenv) a module
+ import a non stdlib module (pandas/numpy/whatever) in your project
+ commit to trigger pre-commit hooks

A possible source of success is which python is used to trigger pdoc within pre-commit. If it's systems default (`python` or `python3`), depending on whether the module is installed or not, it might work.

**Comment by kernc** [comment]
> I looked into my logs and it seems that pre-commit has its own virtualenv

Seems to me the only workaround, then, is to use [repository-local hooks](https://pre-commit.com/#repository-local-hooks)? Something like:
```yaml
-   repo: local
    hooks:
    -   id: pdoc
        name: pdoc
        language: system
        entry: python -m pip install pdoc3 && pdoc --html -f -o docs package
```
:confused:
